### ISSUE TITLE
Should `subgroups` key exist?

### ISSUE THREAD

**Issue by thorehusfeldt** [thorehusfeldt/BAPCtools#1]
It’s much easier to specify
```yaml
wrong_answer/sloppy.py:
  verdict: WA
  sample: AC
  secret: WA
```
Than
```yaml
wrong_answer/sloppy.py:
  verdict: WA
  subgroups:
    sample: AC
    secret: WA
```
However, if we just get rid of the `subgroups` key then there can never be a testgroup called `verdict` (or, for that matter, `score`, which also will be added to the specification.)

This doesn’t seem like a big problem – testgroups are typically called `sample`, `secret`, `group1`, and `huge` – and the lack of freedom for testgroup-naming is amply counterbalanced by the shorter yaml-syntax. Still, probably worth thinking about.
