### ISSUE TITLE
Allow expecations for globs

### ISSUE THREAD

**Issue by thorehusfeldt** [thorehusfeldt/BAPCtools#2]
I want to be able to write this:
```yaml
partially_accepted/th.py:
  sample: AC
  secret:
    group3 : WA
    *: AC
```
with the intention that groups `group1`, `group2`, and `group4` all get `AC`.

This could even make sense for individual testcases:
```
partially_accepted/quadratic.py:
  secret:
    *-tiny-*: AC
    *: TLE
```
with the intention that `004-tiny-connected.in` gets `AC` but `021-edgecase.in` does not.

If the second syntax is allowed, ordering of rules becomes important, and the glob syntax needs do be understood better.
