### ISSUE TITLE
Introduce `required_sub_results` and `forbidden_sub_results`

### ISSUE THREAD

**Issue by thorehusfeldt** [thorehusfeldt/BAPCtools#4]
In the definition of `expected_grades.yaml`, add keys `required_sub_results` and `forbidden_sub_results` for internal nodes like this:
```yaml
secret:
  group1:
    verdict: RTE
    forbidden_sub_results: WA
    required_sub_results: TLE
```
meaning that among the sub-results for `group1` (which must be aggregated to `RTE`), there must be at least one `TLE` verdict, but may be no `WA` verdict. (Both keys can be String or List of strings, though it’s hard to think of many cases where more than one verdict would be specified.)

In particular, forbidding `WA`, say for a quadratic-time submission’s behaviour on a testgroup with large instances, seems to be clearly useful. 

Nice to have, very easy to implement. Makes two more keys ineligible for a testgroup name. Think through what this means for `on_reject: break`.
