### ISSUE TITLE
Introduce `judgemessage`

### ISSUE THREAD

**Issue by thorehusfeldt** [thorehusfeldt/BAPCtools#5]
I want to do this:
```yaml
"wrong_answer/overshoots.py":
  verdict: WA
  judgemessage: Too many rounds
```
The goal is to improve correctness of interactive validators.

Note that `judgemessage`, `teammessage`, and `score` are all useful key names that would correspond to `*.txt` files written by the validator.

By the same logic, one could specify expected messages for multipass (but that then has to be a list).
